version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /Users/gregoryjean-baptiste/Desktop/data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - farmnet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /Users/gregoryjean-baptiste/Desktop/data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - farmnet

  kvstore:
    container_name: kvstore
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
      - farmnet

  server:
    container_name: farm_server
    build: .
    networks:
      - farmnet

networks:
  farmnet:
    driver: bridge